<?php
namespace AUTH\Controller\base;
use PSFS\base\types\Controller;

/**
* Class AUTHBaseController
* @package AUTH\Controller\base* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api AUTH
* Autogenerated controller [2017-04-26 13:39:05]
*/
abstract class AUTHBaseController extends Controller {

    const DOMAIN = 'AUTH';

    /**
    * @Autoload
    * @var \AUTH\Services\AUTHService
    */
    protected $srv;

    /**
    * Constructor por defecto
    */
    function __construct() {
        $this->init();
        $this->setDomain('AUTH')
            ->setTemplatePath(__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'Templates');
    }

}
