checks:
  php: true

build:
  tests:
    override:
      - docker-compose exec -T php sh scrutinizer-tests.sh
  environment:
    docker: true
    variables:
      PHP_VERSION: "8.3"
      DEBUG: ""
  dependencies:
    override:
      - docker-compose up -d php redis
      - docker-compose exec -T php sh prepare-test-runtime.sh
      - docker-compose exec -T php composer install -o --no-interaction --no-progress --prefer-dist
  project_setup:
    override:
      - true

filter:
  excluded_paths:
    - src/bin/*
    - src/command/*
    - src/tests/*
    - src/public/*
    - src/templates/*
    - locale/*
    - cache/*
    - config/*
    - logs/*
    - vendor/*
