checks:
  php: true

build:
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --configuration=src/AUTH/phpunit.xml.dist --coverage-clover=psfs-coverage'
        coverage:
          file: 'psfs-coverage'
          format: 'clover'
  environment:
    php:
      version: "8.3.33"
  dependencies:
    before:
      - sh install-xdebug-for-scrutinizer.sh

filter:
  excluded_paths:
    - src/bin/*
    - src/command/*
    - src/tests/*
    - src/public/*
    - src/templates/*
    - locale/*
    - cache/*
    - config/*
    - logs/*
    - vendor/*
