language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - composer self-update
  - composer install -o

after_deploy:
  - phpunit

addons:
  code_climate:
    repo_token: ada8a3a044a98d6a8ec603521ac59efc9f2f57ad