services:
  php:
    image: stratecode/php:${PHP_VERSION:-8.3}${DEBUG:-}
    restart: always
    tty: true
    volumes:
      - .:/app
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - psfs-auth-network
    working_dir: "/app"
    ports:
      - "${HOST_PORT:-8001}:8080"
    command: 'php -S 0.0.0.0:8080 -t ./html'
    environment:
      XDEBUG_CONFIG: "remote_host=0.0.0.0"
      PHP_IDE_CONFIG: "serverName=PSFSAUTH"
      PHP_TIMEZONE: "${PHP_TIMEZONE:-Europe/Madrid}"
      PHP_OPCACHE: "${PHP_OPCACHE:-0}"
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    restart: always
    image: redis:latest
    networks:
      - psfs-auth-network
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    security_opt:
      - no-new-privileges:true

  db:
    image: mysql
    networks:
      - psfs-auth-network
    environment:
      MYSQL_USER: ${MYSQL_USER:-psfs}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-psfs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-psfs}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-psfs}
    volumes:
      - "psfs_db:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-checks}" ]
      interval: 3s
      timeout: 5s
      retries: 20

networks:
  psfs-auth-network:
    driver: bridge

volumes:
  psfs_db:
