<?php
namespace PSFS\Auth\Controller\base;
use PSFS\base\types\AuthAdminController;

/**
* Class PSFSAuthBaseController
* @package PSFS\Auth\Controller\base* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api PSFS\Auth
* Autogenerated controller [2016-11-07 21:41:02]
*/
abstract class AuthBaseController extends AuthAdminController {

    const DOMAIN = 'AuthBase';

    /**
    * @Inyectable
    * @var \PSFS\Auth\Services\AuthService
    */
    protected $srv;

    /**
    * Constructor por defecto
    */
    function __construct() {
        $this->init();
        $this->setDomain('AuthBase')
            ->setTemplatePath(__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'Templates');
    }

}
