<?php
namespace PSFS\Auth\Services;

use PSFS\base\Service;

/**
* Class AuthService
* @package PSFS\Auth\Services
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated service [2016-11-07 21:41:02]
*/
class AuthService extends Service {
    const EMAIL_LOGIN = 0;
    const GOOGLE_LOGIN = 1;
}
