<?php
namespace PSFS\Auth\Services;

use PSFS\base\Service;

/**
* Class PSFSAuthService
* @package PSFS/Auth\Services
* @author Fran L�pez <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated service [2016-11-07 18:46:02]
*/
class PSFSAuthService extends Service {

}
