<?php
namespace AUTH\Api\base;

use PSFS\base\types\AuthApi;
use AUTH\Models\Map\LoginPathTableMap;

/**
* Class AUTHBaseApi
* @package AUTH\Api\base
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated controller [2019-10-22 00:26:47]
*/
abstract class LoginPathBaseApi extends AuthApi{
    public function getModelTableMap()
    {
        return LoginPathTableMap::class;
    }
}