<?php
namespace AUTH\Api\base;

use PSFS\base\types\AuthApi;
use AUTH\Models\Map\LoginSessionTableMap;

/**
* Class AUTHBaseApi
* @package AUTH\Api\base
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated controller [2017-03-02 10:55:35]
*/
abstract class LoginSessionBaseApi extends AuthApi
{
    public function getModelTableMap()
    {
        return LoginSessionTableMap::class;
    }
}