<?php
namespace AUTH\Api\base;

use \AUTH\Types\SessionAuthApi;
use AUTH\Models\Map\LoginSessionTableMap;

/**
* Class AUTHBaseApi
* @package AUTH\Api\base
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated controller [2017-03-15 23:17:54]
*/
abstract class LoginSessionBaseApi extends SessionAuthApi{
    public function getModelTableMap()
    {
        return LoginSessionTableMap::class;
    }
}