<?php
namespace AUTH\Api\base;

use PSFS\base\types\AuthApi;
use AUTH\Models\Map\LoginLogTableMap;

/**
* Class AUTHBaseApi
* @package AUTH\Api\base
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated controller [2017-03-01 10:06:45]
*/
abstract class LoginLogBaseApi extends AuthApi
{
    public function getModelTableMap()
    {
        return LoginLogTableMap::class;
    }
}