<?php
namespace PSFS\Auth\Controller;
use PSFS\Auth\Controller\base\AuthBaseController;

/**
* Class AuthController
* @package PSFS\Auth\Controller* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api PSFS\Auth
* Autogenerated controller [2016-11-07 21:41:02]
*/
class AuthController extends AuthBaseController {

    /**
     * Index
     * @GET
     * @route /admin/auth
     * @return string HTML
     */
    public function index() {
        return $this->render('index.html.twig');
    }

    /**
     * Index
     * @GET
     * @route /admin/auth/config
     * @return string HTML
     */
    public function config() {
        return $this->render('index.html.twig');
    }

}
