<?php
namespace PSFS\Auth\Controller;

use PSFS\controller\base\Admin;

/**
 * Class PSFSAuthController
 * @package PSFS\Auth\Controller
 * @author Fran López <fran.lopez84@hotmail.es>
 * @version 1.0
 * @Api PSFS\Auth
 * Autogenerated controller [2016-11-07 18:46:02]
 */
class PSFSAuthController extends Admin
{
    const DOMAIN = 'PSFSAuth';

    /**
     * @Inyectable
     * @var \PSFS\Auth\Services\PSFSAuthService
     */
    protected $srv;

    /**
     * Constructor por defecto
     */
    function __construct()
    {
        $this->init();
        $this->setDomain('PSFSAuth')
            ->setTemplatePath(__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'Templates');
    }

    /**
     * Index
     * @GET
     * @route /admin/auth
     * @return string HTML
     */
    public function index()
    {
        return $this->render('index.html.twig');
    }

    /**
     * Config
     * @GET
     * @route /admin/auth/config
     * @return string HTML
     */
    public function config()
    {
        return $this->render('index.html.twig');
    }
}
