<?php
namespace AUTH\Services;

use PSFS\base\Service;

/**
* Class AUTHService
* @package AUTH\Services
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated service [2017-03-02 10:36:03]
*/
class AUTHService extends Service {

}
