<?php
namespace AUTH\Services;

use PSFS\base\Service;

/**
* Class AUTHService
* @package AUTH\Services
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated service [2017-10-12 01:21:07]
*/
class AUTHService extends Service {

}
