<?php
namespace AUTH\Api;

use AUTH\Api\base\LoginSessionBaseApi;
use AUTH\Models\LoginSessionQuery;
use AUTH\Models\Map\LoginAccountTableMap;
use Propel\Runtime\ActiveQuery\ModelCriteria;

/**
* Class AUTH
* @package AUTH\Api
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api LoginSession
* @visible false
* Autogenerated controller [2017-03-02 10:36:04]
*/
class LoginSession extends LoginSessionBaseApi
{
    public function init()
    {
        parent::init();
        $this->extraColumns = [
            'CONCAT(' . LoginAccountTableMap::COL_IDENTIFIER . ', " [", ' . LoginProvider::getListNameSql() . ', "]")' => self::API_LIST_NAME_FIELD
        ];
    }

    public function joinTables(ModelCriteria &$query)
    {
        /** @var LoginSessionQuery $query */
        $query->useAccountSessionQuery()
                ->useAccountProviderQuery()
                ->endUse()
            ->endUse();
    }
}