<?php
namespace AUTH\Api;

use AUTH\Api\base\LoginLogBaseApi;

/**
* Class AUTH
* @package AUTH\Api
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api LoginLog
* Autogenerated controller [2017-02-28 12:23:12]
*/
class LoginLog extends LoginLogBaseApi
{
}