<?php
namespace AUTH\Api;

use AUTH\Api\base\LoginAccountBaseApi;

/**
* Class AUTH
* @package AUTH\Api
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api LoginAccount
* Autogenerated controller [2017-02-20 00:39:30]
*/
class LoginAccount extends LoginAccountBaseApi
{
}