<?php
namespace AUTH\Api;

use AUTH\Api\base\LoginAccountPasswordBaseApi;
use AUTH\Models\LoginAccountPasswordQuery;
use Propel\Runtime\ActiveQuery\ModelCriteria;

/**
* Class AUTH
* @package AUTH\Api
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api LoginAccountPassword
* Autogenerated controller [2019-10-22 00:11:58]
*/
class LoginAccountPassword extends LoginAccountPasswordBaseApi
{
    public function init() {
        parent::init();
        //$this->extraColumns = [];
    }

    public function joinTables(ModelCriteria &$query)
    {
        /** @var LoginAccountPasswordQuery $query */
        //$query;
    }
}