<?php
namespace AUTH\Api;

use AUTH\Api\base\LoginProviderBaseApi;
use AUTH\Models\Map\LoginProviderTableMap;
use AUTH\Services\base\AUTHService;

/**
* Class AUTH
* @package AUTH\Api
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api LoginProvider
* Autogenerated controller [2017-02-20 00:39:30]
*/
class LoginProvider extends LoginProviderBaseApi
{
    public static function getListNameSql() {
        $sql = 'CONCAT(';
        $closeSql = '';
        foreach(LoginProviderTableMap::getValueSet(LoginProviderTableMap::COL_NAME) as $index => $value) {
            $sql .= 'IF(' . LoginProviderTableMap::COL_NAME . ' = ' . $index . ', "' . ucfirst($value) . '", ';
            $closeSql .= ')';
        }
        $sql .= '"Error"';
        $closeSql .= ', " [", IF(' . LoginProviderTableMap::COL_DEV . ' = 0, "Prod", "Dev"), "]")';
        return $sql . $closeSql;
    }

    public function init()
    {
        AUTHService::checkAccess();
        parent::init();
        $this->extraColumns = [
            self::getListNameSql() => self::API_LIST_NAME_FIELD
        ];
    }
}