<?php
namespace AUTH\Api;

use AUTH\Api\base\LoginAccountBaseApi;
use AUTH\Models\LoginAccountQuery;
use AUTH\Models\Map\LoginAccountTableMap;
use AUTH\Services\base\AUTHService;
use Propel\Runtime\ActiveQuery\ModelCriteria;

/**
* Class AUTH
* @package AUTH\Api
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api LoginAccount
* Autogenerated controller [2017-02-20 00:39:30]
*/
class LoginAccount extends LoginAccountBaseApi
{
    public function init()
    {
        AUTHService::checkAccess();
        parent::init();
        $this->extraColumns = [
            'CONCAT(' . LoginProvider::getListNameSql() . ', " ", ' . LoginAccountTableMap::COL_IDENTIFIER . ')' => self::API_LIST_NAME_FIELD
        ];
    }

    public function joinTables(ModelCriteria &$query)
    {
        /** @var LoginAccountQuery $query */
        $query->useAccountProviderQuery()->endUse();
    }
}