<?php
namespace PSFS\Auth\Api;

use PSFS\Auth\Api\base\AccountsArchiveBaseApi;

/**
* Class PSFSAuth
* @package PSFS\Auth\Api
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* @Api AccountsArchive
* Autogenerated controller [2016-11-07 23:30:35]
*/
class AccountsArchive extends AccountsArchiveBaseApi
{
}