ALTER TABLE `auth_providers`
ADD COLUMN `EXPIRATION` tinyint(1) NOT NULL DEFAULT 0 AFTER `ACCOUNTS`,
ADD COLUMN `EXPIRATION_PERIOD` integer(3) NULL AFTER `EXPIRATION`;

DROP TABLE IF EXISTS `AUTH_PATHS`;

CREATE TABLE `AUTH_PATHS`
(
    `ID_PATH` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_PROVIDER` INTEGER NOT NULL,
    `PATH` VARCHAR(500) NOT NULL,
    PRIMARY KEY (`ID_PATH`),
    INDEX `fi_path_provider` (`ID_PROVIDER`),
    CONSTRAINT `fk_path_provider`
        FOREIGN KEY (`ID_PROVIDER`)
        REFERENCES `AUTH_PROVIDERS` (`ID_PROVIDER`)
) ENGINE=InnoDB CHARACTER SET='utf8' COMMENT='Customer provider paths to redirect';

DROP TABLE IF EXISTS `AUTH_ACCOUNT_PASSWORDS`;

CREATE TABLE `AUTH_ACCOUNT_PASSWORDS`
(
    `ID_PASSWORD` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_ACCOUNT` INTEGER NOT NULL,
    `VALUE` VARBINARY(100) NOT NULL,
    `EXPIRATION_DATE` DATETIME NOT NULL,
    `created_at` DATETIME,
    `updated_at` DATETIME,
    PRIMARY KEY (`ID_PASSWORD`),
    INDEX `fi_account_passwords` (`ID_ACCOUNT`),
    CONSTRAINT `fk_account_passwords`
        FOREIGN KEY (`ID_ACCOUNT`)
        REFERENCES `AUTH_ACCOUNTS` (`ID_ACCOUNT`)
) ENGINE=InnoDB CHARACTER SET='utf8' COMMENT='Table with an history for account passwords';