<?php
namespace AUTH\Test;

/**
* Class AUTHTest
* @package AUTH\Test
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated test [2017-03-02 10:55:34]
*/
class AUTHTest extends \PHPUnit\Framework\TestCase {

    public function testAUTHBase() {
        $this->assertTrue(true);
    }
}
