<?php
namespace AUTH\Test;

/**
* Class AUTHTest
* @package AUTH\Test
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated test [2017-03-01 11:22:41]
*/
class AUTHTest extends \PHPUnit_Framework_TestCase {

    public function testAUTHBase() {
        $this->assertTrue(true);
    }
}
