<?php
/**
 * PSFS/Auth Module
 * @author Fran López <fran.lopez84@hotmail.es>
 * @version 1.0
 * Autogenerated autoloader [2016-11-07 18:46:02]
 */
if(!defined("BASE_DIR"))
define("BASE_DIR", dirname( dirname(__DIR__) ) );

require_once __DIR__ . DIRECTORY_SEPARATOR . 'Config' . DIRECTORY_SEPARATOR . 'config.php';

if(!function_exists("PSFS_Auth_Autoloader")) {
    // autoloader
    function PSFS_Auth_Autoloader( $class ) {
        // it only autoload class into the Rain scope
        if (false !== preg_match('/^\\\?PSFS\\\Auth/', $class)) {
            // Change order src
            $class = preg_replace('/^\\\?PSFS\\\Auth/', '', $class);
            // transform the namespace in path
            $path = str_replace("\\", DIRECTORY_SEPARATOR, $class );
            // filepath
            $abs_path = CORE_DIR . DIRECTORY_SEPARATOR . $path . ".php";

            // require the file
            if(file_exists($abs_path)) {
                require_once $abs_path;
            }
        }
        return false;
    }

    // register the autoloader
    spl_autoload_register( "PSFS_Auth_Autoloader" );
}
