<?php
namespace PSFS\Auth\Api\base;

use PSFS\base\types\AuthApi;
use PSFS\Auth\Models\Map\SessionTableMap;

/**
* Class PSFSAuthBaseApi
* @package PSFS\Auth\Api\base
* @author Fran López <fran.lopez84@hotmail.es>
* @version 1.0
* Autogenerated controller [2016-11-07 23:30:35]
*/
abstract class SessionBaseApi extends AuthApi
{
    public function getModelTableMap()
    {
        return SessionTableMap::class;
    }
}